version: '3.3'

services:
  postgres:
    image: 'postgres:15.1-alpine'
    restart: always
    ports:
      - "5532:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: walletdb

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080

  wallet-api:
    image: 'leroidumonde007/wallet:latest'
    depends_on:
      - postgres
    restart: always
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/walletdb
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: password
      WALLET_MAX_OPTIMISTIC_RETRIES: 3