version: '3.3'

services:
  postgres:
    image: 'postgres:15.1-alpine'
    restart: always
    ports:
      - "5532:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: walletdb

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080

  wallet-api:
    image: 'wallet:latest'
    depends_on:
      - postgres
    restart: always
    ports:
      - "8081:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432