spring:
  application:
    name: wallet

  main:
    banner-mode: off

  liquibase:
    enabled: true
    change-log: classpath:changelog-master.yaml

  datasource:
    url: jdbc:postgresql://localhost:5532/walletdb
    username: app
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

logging:
  level:
    org.example.wallet: debug

wallet:
  max-optimistic-retries: 3